extends: ../base.yaml

dataset:
  train_files:
  - "${DATASET}/Assembled_0/train.jsonl"
  eval_files:
  - "${DATASET}/Assembled_0/eval.jsonl"

model:
  model_name: "ibm-granite/granite-3.1-2b-base"

tokens:
  pad_to_eos: true
  add_and_init:
    - { token: "!!no_change!!",    init: "sameSamecopyCopycloneCloneidentical" }
    - { token: "message",          init: "messagenew" }
    - { token: "previousMessage",  init: "messageold" }
    - { token: "stats",            init: "stats" }
    - { token: "unspecified",      init: "undefined" }
    - { token: "nude",             init: "bare" }
    - { token: "genitalia",        init: "sexgender" }
    - { token: " genitalia",        init: " sex gender" }
    - { token: " passages",         init: "doorwindowgate" }
    - { token: " fixtures",         init: "fixturescouchtablebedfloor" }
  grad_boost:
    factor: 10.0
    target: all            # new | all
    apply_to: ["input", "output"]

peft:
  r: full
  modules:
    - embed_tokens
    - lm_head

layerwise_lr:
  base_lr: 5.0e-6

training:
  seed: 42
  dataset_seed: 1234
  output_dir: "${WORK_BASE}/g2b-embed"
  merge_output_dir: "${ARTIFACTORY_BASE}/g2b-embed"
  #merge_output_dir: null
  effective_batch_size: 5
  gradient_accumulation_steps: 1
  warmup_ratio: 0.05
  lr_scheduler_type: constant
  weight_decay: 0.0001
  adam_beta1: 0.9
  adam_beta2: 0.999
  num_train_epochs: 1
  max_grad_norm: 1.0
  logging_steps: 1
  save_strategy: epoch
  save_only_model: true
  eval_strategy: steps
  eval_steps: 100
  eval_on_start: true

gradient_logging:
  enabled: false