extends: ../base.yaml

dataset:
  train_files:
  - "${DATASET}/Assembled_0/train.jsonl"
  eval_files:
  - "${DATASET}/Assembled_0/eval.jsonl"

model:
  model_name: "ibm-granite/granite-3.1-2b-base"

tokens:
  pad_to_eos: true
  train_only_listed: true
  train_only_apply_to:
    - input
    - output
  train_only_weight_decay: 0
  add_and_init:
    - { token: "!!no_change!!",    init: "samecopyidentical" }

    #formatting tokens
    - { token: "message",          init: "messagenew" }
    - { token: "previousMessage",  init: "messageold" }
    - { token: "stats",            init: "stats" }
    - { token: " character",       init: " character" }
    - { token: " scene",           init: " scene" }
    
    #clarity tokens
    - { token: "unspecified",      init: "undefined" }
    - { token: "nude",             init: "bare" }
    - { token: "genitalia",        init: "sexgender" }
    - { token: " genitalia",       init: " sex gender" }

    #stats
    #character: pose, location, outfit, accessories, exposure, bodyState, mood
    - { token: " pose",             init: " pose hold" }
    - { token: " location",         init: " location position" }
    - { token: " outfit",           init: " gear look cover" }
    - { token: " accessories",      init: " ring watch" }
    - { token: " bodystate",        init: " health state" }
    - { token: " mood",             init: " mood emotion" }
    - { token: " exposure",         init: " skin visible" }

    #scene: fixtures, items, passages
    - { token: " passages",         init: "doorwindowgate" }
    - { token: " fixtures",         init: "fixturescouchtablebedfloor" }
    - { token: " items",            init: "itemsthingstoolsobjects" }

  grad_boost:
    factor: 1.0
    target: all            # new | all
    apply_to: ["input", "output"]

peft:
  r: full
  modules:
    - embed_tokens
    - lm_head

layerwise_lr:
  base_lr: 1.0e-4

training:
  seed: 42
  dataset_seed: 1234
  output_dir: "${WORK_BASE}/g2b-embed"
  merge_output_dir: "${ARTIFACTORY_BASE}/g2b-embed"
  #merge_output_dir: null
  effective_batch_size: 20
  gradient_accumulation_steps: 1
  warmup_ratio: 0.1
  lr_scheduler_type: cosine
  weight_decay: 0
  adam_beta1: 0.9
  adam_beta2: 0.999
  num_train_epochs: 1
  max_grad_norm: 1.0
  logging_steps: 1
  save_strategy: epoch
  save_only_model: true
  eval_strategy: steps
  eval_steps: 100
  eval_on_start: true

gradient_logging:
  enabled: false